FROM mongo:5.0.6

# import "users" initial data
COPY data/users.json /users.json
CMD mongoimport --host db --db ongajdb --collection users --type json --file /users.json --jsonArray

# import other things
