# Generated by Django 4.0.4 on 2022-05-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_casts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videocast',
            name='character',
        ),
        migrations.AlterField(
            model_name='videocast',
            name='department',
            field=models.CharField(choices=[('CS', 'Cast'), ('CR', 'Crew'), ('SD', 'Sound'), ('LG', 'Lighting'), ('PD', 'Production'), ('AT', 'Art'), ('ED', 'Editing'), ('CM', 'Costume & Make-Up'), ('CR', 'Camera'), ('DR', 'Directing'), ('VE', 'Visual Effects'), ('AC', 'Actors'), ('WR', 'Writing')], max_length=2, null=True),
        ),
    ]
