# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  # Back-end settings
  # pycln -> isort -> black -> pylint -> django -> pre-commit-hooks -> django-test
  - repo: https://github.com/hadialqattan/pycln
    rev: v1.2.4 # Possible releases: https://github.com/hadialqattan/pycln/releases
    hooks:
      - id: pycln
        name: Remove unused import statements
        language: python
        language_version: python3
        types: [ python ]
        files: ^src/back-end/
        exclude: ^.*\b(migrations)\b.*$
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: Sort import statements
        files: ^src/back-end/
        exclude: ^.*\b(migrations)\b.*$
        args: [ "--filter-files" ]
  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      -  id: black
         types: [python]
         language: python
         files: ^src/back-end/
         exclude: ^.*\b(migrations)\b.*$
         args: ["--line-length=120"]
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        files: ^src/back-end/
        exclude: ^.*\b(migrations)\b.*$
        args: ["--disable=R0903,C0103,W0703,E1101,W0613,W0511,R0201", "--max-line-length=120"]
  - repo: https://github.com/ecugol/pre-commit-hooks-django
    rev: v0.4.0
    hooks:
      - id: check-untracked-migrations
        files: ^src/back-end/
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
        files: ^src/back-end/
      - id: debug-statements
        files: ^src/back-end/
      - id: check-merge-conflict
        files: ^src/back-end/
      - id: requirements-txt-fixer
        files: ^src/back-end/
      - id: end-of-file-fixer
        files: ^src/back-end/
      - id: name-tests-test
        args: ["--django"]
        files: ^src/back-end/
