# Generated by Django 4.0.3 on 2022-04-22 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0003_alter_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemittanceReason',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=10)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Remittance',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('PE', 'PENDING'), ('CA', 'CANCELED'), ('CO', 'COMPLETED')], max_length=2)),
                ('transfer_date_time', models.DateTimeField(null=True)),
                ('payment', models.ForeignKey(db_column='paymentId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.payment')),
                ('reason', models.ForeignKey(db_column='reasonId', default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='remittances.remittancereason')),
                ('user', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'remittances',
            },
        ),
    ]
