# Generated by Django 4.0.3 on 2022-04-22 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_status'),
        ('remittances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remittance',
            name='payment',
            field=models.ForeignKey(blank=True, db_column='paymentId', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.payment'),
        ),
        migrations.AlterField(
            model_name='remittance',
            name='transfer_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
