# Generated by Django 4.0.3 on 2022-04-14 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0002_alter_group_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fellow',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('will_renew', models.BooleanField(db_column='willRenew', default=True)),
                ('creation_date_time', models.DateTimeField(db_column='creationDateTime', default=django.utils.timezone.now)),
                ('last_modification_date_time', models.DateTimeField(db_column='lastModificationDateTime', default=django.utils.timezone.now)),
                ('has_reported', models.BooleanField(db_column='hasReported', default=False)),
                ('group', models.ForeignKey(db_column='groupId', on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
                ('payment', models.ForeignKey(db_column='paymentId', on_delete=django.db.models.deletion.CASCADE, to='payments.payment')),
                ('user', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fellows',
                'ordering': ('-creation_date_time',),
                'unique_together': {('user', 'group')},
            },
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('fellow', models.OneToOneField(db_column='fellowId', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='leader', serialize=False, to='fellows.fellow')),
            ],
            options={
                'db_table': 'leaders',
            },
            bases=('fellows.fellow',),
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('fellow', models.OneToOneField(db_column='fellowId', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='member', serialize=False, to='fellows.fellow')),
                ('has_reported_leader', models.BooleanField(db_column='hasReportedLeader', default=False)),
            ],
            options={
                'db_table': 'members',
            },
            bases=('fellows.fellow',),
        ),
    ]
