# Generated by Django 4.0.4 on 2022-05-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fellows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fellow',
            name='is_leader',
            field=models.BooleanField(default=False),
        ),
    ]
