# Generated by Django 4.0.3 on 2022-04-14 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fellows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leader',
            name='fellow',
            field=models.OneToOneField(db_column='fellowId', on_delete=django.db.models.deletion.CASCADE, to='fellows.fellow'),
        ),
        migrations.AlterField(
            model_name='member',
            name='fellow',
            field=models.OneToOneField(db_column='fellowId', on_delete=django.db.models.deletion.CASCADE, to='fellows.fellow'),
        ),
    ]
