# Generated by Django 4.0.4 on 2022-05-21 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('fellows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fellow',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.payment'),
        ),
    ]
