version : '3'
services:
  # Database for Caching
  cache:
    container_name: redis_prod
    image: redis:latest
    command: redis-server --requirepass ${CACHE_PASSWORD} --port ${CACHE_PORT}
    volumes:
      - ./cache/data:/data
    expose:
      - "${CACHE_PORT}"
    healthcheck:
      test: "redis-cli -h ${CACHE_HOST} ping"
      interval: 3s
      timeout: 1s
      retries: 5
  # WAS
  web:
    container_name: web_prod
    image: web_prod
    build:
      context: .
      dockerfile : web/Dockerfile-prod
      args:
        BASE: ${BASE}
        WEB: ${WEB}
        STATIC: ${STATIC}
        WEB_PORT: ${WEB_PORT}
    command: sh -c "python manage.py prod makemigrations --no-input &&
                    python manage.py prod migrate &&
                    python manage.py prod loaddata data.json &&
                    python manage.py prod collectstatic --no-input &&
                    bash ./config/start.sh"
    restart: on-failure
    volumes:
      - ./web:${WEB}
      - ./environment:${ENV}
    expose:
      - "${WEB_PORT}"
    environment:
      - MODULE_NAME=${MODULE_NAME}
      - VARIABLE_NAME=${VARIABLE_NAME}
      - GUNICORN_CONFIG=${GUNICORN_CONFIG}
      - SETTINGS_MODULE=${SETTINGS_MODULE}
    depends_on:
      - cache
      - broker
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://${WEB_HOST}:${WEB_PORT}" ]
      interval: 1m
      timeout: 10s
      retries: 5
  # Reverse Proxy
  nginx:
    container_name: nginx_prod
    image: nginx:stable
    restart: on-failure
    volumes:
      - ./nginx:/etc/nginx/templates
    environment:
      - WEB_HOST=${WEB_HOST}
      - WEB_DOCKERNAME=${WEB_DOCKERNAME}
      - WEB_PORT=${WEB_PORT}
      - STATIC_LOCATION=${STATIC_LOCATION}
      - MEDIA_LOCATION=${MEDIA_LOCATION}
      - AWS_S3_URL=${AWS_S3_URL}
    ports:
      - "80:80" # http
      - "443:443" # https
    depends_on:
      - web
  # Message broker
  broker:
    container_name: rabbitmq_prod
    image: rabbitmq:3.10.2-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=${BROKER_USER}
      - RABBITMQ_DEFAULT_PASS=${BROKER_PASSWORD}
    ports:
      - "${BROKER_UI_PORT}:${BROKER_UI_PORT}"
    expose:
      - "${BROKER_PORT}"
  # Async Task Queue
  queue:
    container_name: celery_prod
    image: web_prod
    command: sh -c "celery -A config worker --loglevel=info"
    volumes:
      - ./web:${WEB}
      - ./environment:${ENV}
    environment:
      - MODULE_NAME=${MODULE_NAME}
      - VARIABLE_NAME=${VARIABLE_NAME}
      - GUNICORN_CONFIG=${GUNICORN_CONFIG}
      - SETTINGS_MODULE=${SETTINGS_MODULE}
    depends_on:
      - web
