version : '3'
services:
  mongo:
    container_name: mongo_prod
    image: mongo:5.0.6
    restart: on-failure
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${DB_HOST}:${DB_PORT}"]
      interval: 1m
      timeout: 15s
      retries: 5

#  mongo-seed:
#    build:
#      context: ./mongo
#      dockerfile : Dockerfile-prod
#      args:
#        DB_NAME: ${DB_NAME}
#    depends_on:
#      - mongo

  web:
    container_name: web_prod
    build:
      context: .
      dockerfile : web/Dockerfile-prod
      args:
        BASE: ${BASE}
        WEB: ${WEB}
        STATIC: ${STATIC}
        WEB_PORT: ${WEB_PORT}
    command: sh -c "python manage.py prod makemigrations &&
                    python manage.py prod migrate &&
                    python manage.py prod collectstatic --no-input &&
                    bash ./config/start.sh"
    restart: on-failure
    volumes:
      - ./web:${WEB}
      - ./environment:${ENV}
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    environment:
      - MODULE_NAME=${MODULE_NAME}
      - VARIABLE_NAME=${VARIABLE_NAME}
    depends_on:
      - mongo
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://${WEB_HOST}:${WEB_PORT}" ]
      interval: 30s
      timeout: 10s
      retries: 5

  nginx:
    container_name: nginx_prod
    image: nginx:stable
    restart: on-failure
    volumes:
      - ./nginx:/etc/nginx/templates
    environment:
      - WEB_HOST=${WEB_HOST}
      - AWS_STATIC_LOCATION=${AWS_STATIC_LOCATION}
      - AWS_MEDIA_LOCATION=${AWS_MEDIA_LOCATION}
      - AWS_S3_URL=${AWS_S3_URL}
    ports:
      - "80:80" # http
      - "443:443" # https
    depends_on:
      - web
