version : '3'
services:
  db:
    container_name: mongo_service
    image: mongo:5.0.6
    restart: on-failure
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PORT}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    command: -port ${DB_PORT}

#  mongo-seed:
#    build:
#      context: ./mongo
#      dockerfile : Dockerfile-dev
#    depends_on:
#      - mongo

  web:
    container_name: web_service
    build:
      context: ./web
      dockerfile : Dockerfile-dev
      args:
        WEB: ${WEB}
        STATIC: ${STATIC}
        WEB_PORT: ${WEB_PORT}
    command: sh -c "python manage.py dev collectstatic --no-input &&
                    python manage.py dev makemigrations &&
                    python manage.py dev migrate &&
                    python manage.py dev collectstatic"
    environment:
      - DB_NAME=${DB_NAME}
      - DB_ENFORCE_SCHEMA=True
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    depends_on:
      - db

  nginx:
    container_name: nginx_service
    build:
      context: ./nginx
      dockerfile: Dockerfile-dev
    volumes:
      - ./nginx:${NGINX}
      - ./web/static:${STATIC}
    environment:
      - WEB_HOST=${WEB_HOST}
      - WEB_DOCKERNAME=${WEB_DOCKERNAME}
    ports:
      - "80:80" # http
      - "443:443" # https
    depends_on:
      - web
