version : '3'
services:
  db:
    container_name: mongo_service
    image: mongo:5.0.6
    restart: on-failure
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
    volumes:
      - ./db:/docker-entrypoint-initdb.d:ro
      - ./db:${DB}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    command: -port ${DB_PORT}

#  db-seed:
#    build:
#      context: ./db
#      dockerfile : Dockerfile-prod
#    depends_on:
#      - db

  web:
    container_name: web_service
    build:
      context: ./web
      dockerfile : Dockerfile-prod
      args:
        WEB: ${WEB}
        STATIC: ${STATIC}
        WEB_PORT: ${WEB_PORT}
    command: sh -c "python manage.py prod collectstatic --no-input &&
                    python manage.py prod makemigrations &&
                    python manage.py prod migrate &&
                    python manage.py prod initiate_admin &&
                    python manage.py prod collectstatic"
    environment:
      - DB_NAME=${DB_NAME}
      - DB_ENFORCE_SCHEMA=True
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    depends_on:
      - db

  nginx:
    container_name: nginx_service
    build:
      context: ./nginx
      dockerfile: Dockerfile-prod
    volumes:
      - ./nginx:${NGINX}
      - ./web/static:${STATIC}
    environment:
      - WEB_HOST=${WEB_HOST}
      - WEB_DOCKERNAME=${WEB_DOCKERNAME}
    ports:
      - "80:80" # http
      - "443:443" # https
    depends_on:
      - web
