### Build application
FROM node:lts as build

# Set environment variables
ENV APP=/
ENV APP_BUILD=/dist

# Set working directory
RUN mkdir -p $APP_BUILD
WORKDIR ${APP}

# Copy package
COPY ./package.json ./package.json
COPY ./package-lock.json ./package-lock.json

# Install dependencies
RUN npm install

# Copy project
COPY . .

# Build local version
RUN npm run local


### Deploy vue project
FROM nginx:stable as deploy

# Set environment variables
ENV APP_PORT=8080
ENV APP_BUILD=/dist
ENV APP_HOST=localhost
ENV APP_LOCATION=/usr/share/nginx/html/

# Copy settings
COPY ./nginx/default.conf.template /etc/nginx/conf.d/default.conf.template

# Copy files
COPY --from=build ${APP_BUILD} ${APP_LOCATION}

# Set port
EXPOSE ${APP_PORT}

# Set environment variables
COPY ./docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh
ENTRYPOINT ["/docker-entrypoint.sh"]

## Start proxy server
CMD ["nginx", "-g", "daemon off;"]
