# Generated by Django 4.0.3 on 2022-04-23 03:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tmdb_id', models.PositiveBigIntegerField(db_column='tmdbId')),
                ('name', models.CharField(choices=[('NF', 'Netflix'), ('WC', 'Watcha'), ('DP', 'DisneyPlus'), ('TV', 'Tving'), ('WV', 'Wavve')], max_length=2)),
                ('logo_key', models.CharField(db_column='logoKey', max_length=100)),
            ],
            options={
                'db_table': 'providers',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionType',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('number_of_subscribers', models.PositiveSmallIntegerField(db_column='numberOfSubscribers')),
                ('detail', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'subscription_types',
            },
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('service_charge_per_member', models.PositiveIntegerField(db_column='serviceChargePerMember', default=0)),
                ('subscription_charge_per_member', models.PositiveIntegerField(db_column='subscriptionChargePerMember', default=0)),
                ('total_subscription_charge', models.PositiveIntegerField(db_column='totalSubscriptionCharge', default=0)),
                ('base_date', models.DateField(db_column='baseDate', default=django.utils.timezone.now)),
                ('provider', models.ForeignKey(db_column='provider', on_delete=django.db.models.deletion.CASCADE, to='providers.provider')),
                ('subscription_type', models.ForeignKey(db_column='subscriptionType', null=True, on_delete=django.db.models.deletion.SET_NULL, to='providers.subscriptiontype')),
            ],
            options={
                'db_table': 'charges',
            },
        ),
    ]
