# Generated by Django 4.0.3 on 2022-03-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='logo_key',
            field=models.CharField(db_column='logoKey', max_length=100),
        ),
    ]
