# Generated by Django 4.0.4 on 2022-05-20 01:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_provider_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontype',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(days=30)),
        ),
        migrations.AlterField(
            model_name='charge',
            name='provider',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='providers.provider'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='subscription_type',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='providers.subscriptiontype'),
        ),
    ]
