# Generated by Django 4.0.3 on 2022-04-14 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_alter_provider_logo_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(choices=[('NF', 'Netflix'), ('WC', 'Watcha'), ('DP', 'DisneyPlus'), ('TV', 'Tving'), ('WV', 'Wavve')], max_length=2),
        ),
    ]
