# Generated by Django 4.0.4 on 2022-05-20 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_subscriptiontype_duration_alter_charge_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='subscription_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='providers.subscriptiontype'),
        ),
    ]
