# Generated by Django 4.0.4 on 2022-05-20 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0004_alter_charge_subscription_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptiontype',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
