# Generated by Django 4.0.4 on 2022-05-12 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TvSeriesDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_seasons', models.PositiveIntegerField(default=1)),
                ('number_of_episodes', models.PositiveIntegerField(default=1)),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='videos.video')),
            ],
            options={
                'db_table': 'tv_series_details',
            },
        ),
        migrations.CreateModel(
            name='TvSeasonDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_total_episodes', models.PositiveIntegerField(null=True)),
                ('trailer_key', models.URLField(max_length=100, null=True)),
                ('number', models.PositiveIntegerField(default=0)),
                ('tmdb_number', models.PositiveIntegerField()),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tv_details.tvseriesdetail')),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='videos.video')),
            ],
            options={
                'db_table': 'tv_season_details',
            },
        ),
        migrations.CreateModel(
            name='TvSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('number', models.PositiveIntegerField()),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tv_details.tvseriesdetail')),
            ],
            options={
                'db_table': 'tv_seasons',
            },
        ),
    ]
