# Generated by Django 4.0.4 on 2022-05-04 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tv_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvseason',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tv_details.tvseriesdetail'),
        ),
    ]
