# Generated by Django 4.0.4 on 2022-05-28 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_details', '0002_alter_tvseason_series'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tvseasondetail',
            name='tmdb_number',
        ),
        migrations.AddField(
            model_name='tvseasondetail',
            name='overview',
            field=models.TextField(null=True),
        ),
    ]
