# Generated by Django 4.0.4 on 2022-05-28 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_alter_videodetail_video'),
        ('tv_details', '0003_remove_tvseasondetail_tmdb_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvseasondetail',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.video'),
        ),
    ]
