# Generated by Django 4.0.4 on 2022-05-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_details', '0004_alter_tvseasondetail_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tvseasondetail',
            name='trailer_key',
        ),
        migrations.AddField(
            model_name='tvseriesdetail',
            name='trailer_key',
            field=models.URLField(max_length=100, null=True),
        ),
    ]
