# Generated by Django 4.0.4 on 2022-06-01 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_details', '0005_remove_tvseasondetail_trailer_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tvseasondetail',
            name='video',
        ),
        migrations.AlterField(
            model_name='tvseasondetail',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
    ]
