# Generated by Django 4.0.4 on 2022-05-02 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gerne',
            new_name='Genre',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='video_id',
            new_name='video',
        ),
        migrations.RenameField(
            model_name='productioncountry',
            old_name='video_id',
            new_name='video',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='video_id',
            new_name='video',
        ),
        migrations.AlterModelTable(
            name='genre',
            table='genres',
        ),
    ]
