# Generated by Django 4.0.4 on 2022-05-02 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_rename_gerne_genre_rename_video_id_genre_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.video'),
        ),
        migrations.AlterField(
            model_name='productioncountry',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.video'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.video'),
        ),
    ]
