# Generated by Django 4.0.4 on 2022-05-03 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_alter_genre_video_alter_productioncountry_video_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videodetail',
            old_name='video_id',
            new_name='video',
        ),
    ]
