# Generated by Django 4.0.4 on 2022-05-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_rename_video_id_videodetail_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='poster_key',
        ),
        migrations.AddField(
            model_name='video',
            name='poster_url',
            field=models.URLField(null=True),
        ),
    ]
