"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import os.path
from pathlib import Path

# web
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent  # web
BACKEND_DIR = BASE_DIR.parent
ENV_DIR = os.path.join(BACKEND_DIR, "environment")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Application definition

CUSTOM_APPS = [
    "users",
    "accounts",
    "applies",
    "wishes",
    "fellows",
    "group_accounts",
    "groups",
    "mileages",
    "notifications",
    "payments",
    "providers",
    "recent_views",
    "remittances",
    "star_ratings",
    "videos",
    "watching_marks",
]

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # django-rest-framework
    "rest_framework",
    "storages",
    "drf_spectacular",
] + CUSTOM_APPS

REST_FRAMEWORK = {
    # API document automation: drf-spectacular
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",  # i18n
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

USE_I18N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/
STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BACKEND_DIR, "static/")  # caution

# Media files
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BACKEND_DIR, "media/")  # caution

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LANGUAGE_CODE = "ko-kr"

# CORS
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = (
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
)

CORS_ALLOW_HEADERS = [
    "accept",
    "host",
    "x-real-ip",
    "x-forwarded-for",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "location",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

# SSL settings
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True

# user model
AUTH_USER_MODEL = "users.User"

# API document automation (drf-spectacular)
SPECTACULAR_SETTINGS = {
    "TITLE": "온갖(Ongot) API",
    "DESCRIPTION": "[다학제간캡스톤디자인I] 24조",
    "CONTACT": {
        "name": "팀 뫄뫄",
        "url": "https://github.com/kookmin-sw/capstone-2022-24",
        "email": "kmu.sw.cap.2022@gmail.com",
    },
    "VERSION": "0.0.1",
    "SERVE_INCLUDE_SCHEMA": False,
    # list of authentication/permission classes for spectacular's views.
    "SERVE_PERMISSIONS": ["rest_framework.permissions.AllowAny"],
    # None will default to DRF's AUTHENTICATION_CLASSES
    "SERVE_AUTHENTICATION": None,
    # Initialize SwaggerUI with additional OAuth2 configuration.
    # https://swagger.io/docs/open-source-tools/swagger-ui/usage/oauth2/
    "SWAGGER_UI_OAUTH2_CONFIG": {},
    # Postprocessing functions that run at the end of schema generation.
    # must satisfy interface result = hook(generator, request, public, result)
    "POSTPROCESSING_HOOKS": ["drf_spectacular.hooks.postprocess_schema_enums"],
    # Preprocessing functions that run before schema generation.
    # must satisfy interface result = hook(endpoints=result) where result
    # is a list of Tuples (path, path_regex, method, callback).
    "PREPROCESSING_HOOKS": [],
    # Determines how operations should be sorted. If you intend to do sorting with a
    # PREPROCESSING_HOOKS, be sure to disable this setting. If configured, the sorting
    # is applied after the PREPROCESSING_HOOKS. Accepts either
    # True (drf-spectacular's alpha-sorter), False, or a callable for sort's key arg.
    "SORT_OPERATIONS": True,
    # Camelize names like operationId and path parameter names
    "CAMELIZE_NAMES": False,
    # Runs exemplary schema generation and emits warnings as part of "./manage.py check --deploy"
    "ENABLE_DJANGO_DEPLOY_CHECK": True,
    # TODO
    # Optional list of servers.
    "SERVERS": [
        {"url": "http://localhost:80/", "description": "Local server"},
        {"url": "https://development.server.link.todo/", "description": "Development server"},
        {"url": "https://main.server.link.todo/", "description": "Main server"},
    ],
    # Tags defined in the global scope
    "TAGS": [
        {"name": "User", "description": "사용자 API"},
        {"name": "Video", "description": "작품 API"},
        {"name": "Group", "description": "모임 API"},
        {"name": "Priority-1", "description": "1순위 API"},
        {"name": "Priority-2", "description": "2순위 API"},
        {"name": "Priority-3", "description": "3순위 API"},
        {"name": "Priority-4", "description": "4순위 API"},
    ],
    # TODO
    # Oauth2 related settings. used for example by django-oauth2-toolkit.
    # https://spec.openapis.org/oas/v3.0.3#oauthFlowsObject
    "OAUTH2_FLOWS": [],
    "OAUTH2_AUTHORIZATION_URL": None,
    "OAUTH2_TOKEN_URL": None,
    "OAUTH2_REFRESH_URL": None,
    "OAUTH2_SCOPES": None,
    "SWAGGER_UI_SETTINGS": {
        "dom_id": "#swagger-ui",  # required(default)
        "layout": "BaseLayout",  # required(default)
        "filter": True,
        "deepLinking": True,
        "persistAuthorization": True,
        "displayOperationId": True,
    },
}

# i18n
LANGUAGE_CODE = "ko"

LANGUAGES = [
    ("ko", "Korean"),
    ("en-us", "English"),
]

LOCALE_PATHS = [os.path.join(BACKEND_DIR, "locale")]  # src/back-end/locale
