# Generated by Django 4.0.4 on 2022-05-12 16:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
        ('group_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Recruiting', '모집중'), ('Recruited', '모집완료'), ('Reviewing', '검토중'), ('Watching', '관람중')], default='Recruiting', max_length=10)),
                ('creation_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_watching_date_time', models.DateTimeField(blank=True, null=True)),
                ('end_watching_date_time', models.DateTimeField(blank=True, null=True)),
                ('group_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_accounts.groupaccount')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.provider')),
            ],
            options={
                'db_table': 'group',
            },
        ),
    ]
