# Generated by Django 4.0.3 on 2022-04-14 04:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group_accounts', '0002_alter_groupaccount_creation_date_time_and_more'),
        ('providers', '0002_alter_provider_logo_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Recruiting', '모집중'), ('Recruited', '모집완료'), ('Reviewing', '검토중'), ('Watching', '관람중')], max_length=10)),
                ('creation_date_time', models.DateTimeField(db_column='creationDateTime', default=django.utils.timezone.now)),
                ('start_watching_date_time', models.DateTimeField(blank=True, db_column='startWatchingDateTime', null=True)),
                ('end_watching_date_time', models.DateTimeField(blank=True, db_column='endWatchingDateTime', null=True)),
                ('group_account', models.ForeignKey(db_column='groupAccountId', on_delete=django.db.models.deletion.CASCADE, to='group_accounts.groupaccount')),
                ('provider', models.ForeignKey(db_column='providerId', on_delete=django.db.models.deletion.CASCADE, to='providers.provider')),
            ],
            options={
                'db_table': 'groups',
            },
        ),
    ]
