# Generated by Django 4.0.3 on 2022-04-14 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='status',
            field=models.CharField(choices=[('Recruiting', '모집중'), ('Recruited', '모집완료'), ('Reviewing', '검토중'), ('Watching', '관람중')], default='Recruiting', max_length=10),
        ),
    ]
