# Generated by Django 4.0.4 on 2022-05-11 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group_accounts', '0001_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='group_accounts.groupaccount'),
        ),
    ]
