# Generated by Django 4.0.4 on 2022-05-20 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_group_group_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='status',
            field=models.CharField(choices=[('Recruiting', '모집중'), ('Recruited', '모집완료'), ('Watching', '관람중')], default='Recruiting', max_length=10),
        ),
    ]
