# Generated by Django 4.0.4 on 2022-05-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_alter_group_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='status',
            field=models.CharField(choices=[('Recruiting', '모집중'), ('Recruited', '모집완료'), ('Watching', '관람중')], default='Recruited', max_length=10),
        ),
    ]
