# Generated by Django 4.0.3 on 2022-03-30 07:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('content', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('n', 'NORMAL'), ('b', 'BILLING'), ('c', 'CONNECTPAY')], max_length=1)),
                ('method', models.CharField(choices=[('Card', '카드'), ('Virtual', '가상계좌'), ('Phone', '휴대폰'), ('Transfer', '계좌이체'), ('Voucher', '상품권')], max_length=10)),
                ('status', models.CharField(choices=[('r', 'READY'), ('i', 'IN_PROGRESS'), ('w', 'WAITING_FOR_DEPOSIT'), ('d', 'DONE'), ('c', 'CANCELED'), ('p', 'PARTIAL_CANCELED'), ('a', 'ABORTED'), ('e', 'EXPIRED')], default='r', max_length=1)),
                ('request_date_time', models.DateTimeField(db_column='requestDateTime', default=django.utils.timezone.now)),
                ('approval_date_time', models.DateTimeField(blank=True, db_column='approvalDateTime', null=True)),
            ],
            options={
                'db_table': 'payments',
            },
        ),
    ]
