# Generated by Django 4.0.3 on 2022-04-14 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_category_alter_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('R', 'READY'), ('I', 'IN_PROGRESS'), ('W', 'WAITING_FOR_DEPOSIT'), ('D', 'DONE'), ('C', 'CANCELED'), ('P', 'PARTIAL_CANCELED'), ('A', 'ABORTED'), ('E', 'EXPIRED')], default='R', max_length=1),
        ),
    ]
