# Generated by Django 4.0.4 on 2022-05-12 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overview', models.TextField(null=True)),
                ('trailer_key', models.URLField(max_length=150, null=True)),
                ('source', models.CharField(max_length=50, null=True)),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='videos.video')),
            ],
            options={
                'db_table': 'movie_details',
            },
        ),
    ]
