FROM nginx:stable

COPY nginx.conf /etc/nginx/conf.d

CMD ["/bin/bash", "-c", "envsubst '$${WEB_HOST} $${BASE} $${AWS_S3_URL}'< /etc/nginx/templates/nginx.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"]
