FROM nginx:stable

COPY nginx.conf /etc/nginx/conf.d

CMD ["/bin/bash", "-c", "envsubst '$${WEB_HOST} $${WEB_DOCKERNAME}' < /etc/nginx/conf.d/nginx.conf > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"]
