FROM nginx:stable

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d

CMD ["/bin/sh" , "-c" , "envsubst '$NGINX_PORT1 $NGINX_PORT2 $WEB_DOCKERNAME $WEB_HOST' < /nginx.conf.template > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"]
