# Generated by Django 4.0.3 on 2022-04-05 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'banks',
            },
        ),
        migrations.DeleteModel(
            name='accounts',
        ),
        migrations.DeleteModel(
            name='banks',
        ),
        migrations.AddField(
            model_name='account',
            name='bank',
            field=models.ForeignKey(db_column='bankId', on_delete=django.db.models.deletion.CASCADE, to='accounts.bank'),
        ),
    ]
