# Generated by Django 4.0.3 on 2022-04-23 03:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('N', 'Naver'), ('G', 'Google')], max_length=1)),
                ('logo_key', models.CharField(db_column='logoKey', max_length=100)),
            ],
            options={
                'db_table': 'social_types',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=8, unique=True)),
                ('email', models.EmailField(max_length=50)),
                ('cell_phone_number', models.CharField(db_column='cellPhoneNumber', max_length=14)),
                ('profile_image_url', models.ImageField(blank=True, db_column='profileImageUrl', null=True, upload_to='')),
                ('birthday', models.DateField()),
                ('is_active', models.BooleanField(db_column='isActive', default=True)),
                ('is_admin', models.BooleanField(db_column='isAdmin', default=False)),
                ('total_mileages', models.PositiveIntegerField(db_column='totalMileages', default=0)),
                ('withdrawal_date_time', models.DateTimeField(blank=True, db_column='withdrawalDateTime', null=True)),
                ('registration_date_time', models.DateTimeField(db_column='registrationDateTime', default=django.utils.timezone.now)),
                ('last_login_date_time', models.DateTimeField(blank=True, db_column='lastLoginDateTime', null=True)),
                ('social_type', models.ForeignKey(db_column='socialTypeId', default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='users.socialtype')),
            ],
            options={
                'db_table': 'users',
                'ordering': ('-registration_date_time',),
            },
        ),
    ]
