# Generated by Django 4.0.3 on 2022-03-27 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SocialType',
            new_name='social_types',
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='users',
        ),
        migrations.RenameField(
            model_name='social_types',
            old_name='logo_key',
            new_name='logoKey',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='withdrawal_date_time',
            new_name='withdrawalDateTime',
        ),
    ]
