# Generated by Django 4.0.4 on 2022-05-01 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='social_type',
        ),
    ]
