# Generated by Django 4.0.4 on 2022-04-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialtype',
            name='name',
            field=models.CharField(choices=[('N', 'Naver'), ('G', 'Google'), ('O', 'Others')], max_length=1),
        ),
    ]
