# Generated by Django 4.0.4 on 2022-05-10 03:16

import django.core.validators
from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cell_phone_number',
            field=models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(code='invalid_cell_phone_number', message='핸드폰 번호는 01X-XXX-XXXX 혹은 01X-XXXX-XXXX 형식이어야 합니다.', regex='^01\\d-\\d{3,4}-\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=8, unique=True, validators=[users.validators.BaseValidatorWithCode(code='invalid_min_length', validator=django.core.validators.MinLengthValidator(1, message='닉네임은 1자 이상 입력해야 합니다.')), users.validators.BaseValidatorWithCode(code='invalid_max_length', validator=django.core.validators.MaxLengthValidator(8, message='닉네임은 최대 8자까지 입력 가능합니다.')), django.core.validators.RegexValidator(code='invalid_characters', message='닉네임은 한글, 숫자, 영문자만 사용 가능합니다.', regex='^[가-힣a-zA-Z0-9]+$')]),
        ),
    ]
