# Generated by Django 4.0.3 on 2022-04-14 02:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0002_alter_provider_logo_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderApply',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('apply_date_time', models.DateTimeField(db_column='applyDateTime', default=django.utils.timezone.now)),
                ('payment', models.ForeignKey(db_column='paymentId', on_delete=django.db.models.deletion.CASCADE, to='payments.payment')),
                ('provider', models.ForeignKey(db_column='providerId', on_delete=django.db.models.deletion.CASCADE, to='providers.provider')),
                ('user', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leader_applies',
            },
        ),
    ]
