# Generated by Django 4.0.3 on 2022-04-14 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applies', '0002_alter_leaderapply_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaderapply',
            options={'verbose_name_plural': 'Leader Applies'},
        ),
    ]
