# Generated by Django 4.0.4 on 2022-05-20 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('applies', '0002_alter_leaderapply_payment_alter_memberapply_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderapply',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.payment'),
        ),
        migrations.AlterField(
            model_name='memberapply',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.payment'),
        ),
    ]
