# Generated by Django 4.0.4 on 2022-05-23 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0007_alter_provider_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
        ('applies', '0006_baseapply_fellow_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('fellow_type', models.CharField(choices=[('M', '모임원'), ('L', '모임장')], default='M', max_length=1)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.payment')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.provider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-apply_date_time',),
                'unique_together': {('user', 'provider')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='baseapply',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='baseapply',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='baseapply',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='baseapply',
            name='user',
        ),
        migrations.DeleteModel(
            name='LeaderApply',
        ),
        migrations.DeleteModel(
            name='MemberApply',
        ),
        migrations.DeleteModel(
            name='BaseApply',
        ),
    ]
