# Generated by Django 4.0.4 on 2022-05-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applies', '0007_groupapply_alter_baseapply_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupapply',
            name='fellow_type',
            field=models.CharField(choices=[('M', '모임원'), ('L', '모임장')], max_length=1),
        ),
    ]
