# Generated by Django 4.0.4 on 2022-05-31 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applies', '0008_alter_groupapply_fellow_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupapply',
            name='fellow_type',
            field=models.CharField(choices=[('M', 'member'), ('L', 'leader')], max_length=1),
        ),
    ]
