# Generated by Django 4.0.4 on 2022-05-03 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('P001', '결제 완료'), ('G001', '모임 신청 완료'), ('G002', '모집 완료'), ('G003', '검토 요청'), ('G004', '관람 기간'), ('G005', '연장 취소'), ('G006', '구독 연장'), ('G007', '모임 연장'), ('G008', '모임 해체'), ('G009', '모임 완주'), ('A001', '계정 대기'), ('A002', '계정 등록 요청'), ('R001', '모임장 신고'), ('R002', '모임 신고'), ('P002', '결제 요청'), ('M001', '마일리지 사용'), ('M002', '마일리지 적립')], max_length=4)),
                ('message', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'notification_content',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_read', models.BooleanField(default=False)),
                ('creation_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.notificationcontent')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.provider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification',
            },
        ),
    ]
