# Generated by Django 4.0.4 on 2022-06-02 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationcontent',
            name='category',
            field=models.CharField(choices=[('P', '결제'), ('G', '모임'), ('M', '마일리지'), ('R', '신고'), ('A', '계정'), ('B', '정지'), ('O', '기타')], default='O', max_length=1),
        ),
        migrations.AlterField(
            model_name='notificationcontent',
            name='code',
            field=models.CharField(choices=[('P001', '결제 완료'), ('P002', '결제 요청'), ('G001', '모임 신청 완료'), ('G002', '모집 완료'), ('G003', '검토 요청'), ('G004', '관람 기간'), ('G005', '연장 취소'), ('G006', '구독 연장'), ('G007', '모임 연장'), ('G008', '모임 해체'), ('G009', '모임 완주'), ('A001', '계정 대기'), ('A002', '계정 등록 요청'), ('A002', '계정 정보 등록'), ('R001', '모임장 신고'), ('R002', '모임 신고'), ('M001', '마일리지 사용'), ('M002', '마일리지 적립')], max_length=4),
        ),
    ]
