# Generated by Django 4.0.4 on 2022-06-02 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationcontent_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='deadline_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificationcontent',
            name='code',
            field=models.CharField(choices=[('P001', '결제 완료'), ('P002', '결제 요청'), ('G001', '모임 신청 완료'), ('G002', '모집 완료'), ('G003', '검토 요청'), ('G004', '관람 기간'), ('G005', '연장 취소'), ('G006', '구독 연장'), ('G007', '모임 연장'), ('G008', '모임 해체'), ('G009', '모임 완주'), ('A001', '계정 대기'), ('A002', '계정 등록 요청'), ('A002', '계정 정보 등록'), ('R001', '모임장 신고'), ('R002', '모임 신고'), ('M001', '사용 완료'), ('M002', '적립 완료')], max_length=4),
        ),
        migrations.AlterUniqueTogether(
            name='notificationcontent',
            unique_together={('category', 'code')},
        ),
    ]
