# Generated by Django 4.0.3 on 2022-04-28 21:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0003_alter_provider_name'),
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoProvider',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('offer_type', models.CharField(choices=[(None, 'None_information'), ('flatrate', 'flatrate'), ('rent', 'rent'), ('buy', 'buy')], db_column='offerType', max_length=8, null=True)),
                ('link', models.URLField()),
                ('offer_date', models.DateField(db_column='offerDate', default=django.utils.timezone.now, null=True)),
                ('deadline', models.DateField(default=django.utils.timezone.now)),
                ('provider', models.ForeignKey(db_column='providerId', on_delete=django.db.models.deletion.CASCADE, to='providers.provider')),
                ('video', models.ForeignKey(db_column='videoId', on_delete=django.db.models.deletion.CASCADE, to='videos.video')),
            ],
            options={
                'db_table': 'video_providers',
            },
        ),
    ]
