# Generated by Django 4.0.4 on 2022-05-16 11:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_type', models.CharField(choices=[(None, 'None_information'), ('flatrate', 'flatrate'), ('rent', 'rent'), ('buy', 'buy')], max_length=8, null=True)),
                ('link', models.URLField()),
                ('offer_date', models.DateField(default=django.utils.timezone.now)),
                ('deadline', models.DateField(default=django.utils.timezone.now, null=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.provider')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.video')),
            ],
            options={
                'db_table': 'video_providers',
            },
        ),
    ]
