FROM python:3.9

LABEL maintainer="Sebastian Ramirez <tiangolo@gmail.com>"

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ARG BASE
ARG WEB
ARG STATIC
ARG WEB_PORT

ENV MODULE_NAME=config.main
ENV VARIABLE_NAME=application

# Set working directory
RUN mkdir -p $WEB
RUN mkdir -p $STATIC
WORKDIR ${WEB}

# Copy Requirements
COPY ./web/requirements.txt ./requirements.txt

# Install dependencies
RUN pip install --no-cache-dir --upgrade -r requirements.txt

# Copy project
COPY ./web .

# Copy environment variables
COPY env정ironment ${BASE}

# shell script
RUN chmod +x ./config/start.sh
RUN chmod +x ./config/start-reload.sh

ENV PYTHONPATH=${WEB}

# Expose port for running the application
EXPOSE ${WEB_PORT}
