FROM python:3.9

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ARG WEB
ARG STATIC
ARG WEB_PORT

# Set working directory
RUN mkdir -p $WEB
RUN mkdir -p $STATIC
WORKDIR ${WEB}

# Copy Requirements
COPY ./web/requirements.txt ./requirements.txt

# Install dependencies
RUN pip install --no-cache-dir --upgrade -r requirements.txt

# Copy project
COPY ./web .

# Copy environment variables
COPY ./.env.local ${BASE}

RUN ls ${BASE}

RUN chmod +x ./config/start.sh
RUN chmod +x ./config/start-reload.sh

ENV PYTHONPATH=${WEB}

# Expose port for running the application
EXPOSE ${WEB_PORT}

# Start gunicorn with uvicorn
CMD ["./config/start.sh"]
