# Generated by Django 4.0.3 on 2022-04-28 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoTotalCount',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dibs_count', models.IntegerField(db_column='dibsCount', default=0, null=True)),
                ('watch_count', models.IntegerField(db_column='watchCount', default=0, null=True)),
                ('view_count', models.IntegerField(db_column='viewCount', default=0, null=True)),
                ('video', models.ForeignKey(db_column='videoId', on_delete=django.db.models.deletion.CASCADE, to='videos.video')),
            ],
            options={
                'db_table': 'video_total_counts',
            },
        ),
    ]
