# Generated by Django 4.0.4 on 2022-05-12 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoTotalCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibs_count', models.PositiveIntegerField(default=0, null=True)),
                ('watch_count', models.PositiveIntegerField(default=0, null=True)),
                ('view_count', models.PositiveIntegerField(default=0, null=True)),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='videos.video')),
            ],
            options={
                'db_table': 'video_total_counts',
            },
        ),
    ]
