# Generated by Django 4.0.4 on 2022-05-19 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_total_counts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videototalcount',
            name='dibs_count',
        ),
        migrations.AddField(
            model_name='videototalcount',
            name='wish_count',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
