# Generated by Django 4.0.3 on 2022-04-14 04:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupAccount',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=30, null=True)),
                ('creation_date_time', models.DateTimeField(db_column='creationDateTime', default=django.utils.timezone.now, null=True)),
                ('last_modification_date_time', models.DateTimeField(db_column='lastModificationDateTime', default=django.utils.timezone.now, null=True)),
            ],
            options={
                'db_table': 'group_accounts',
            },
        ),
    ]
