# Generated by Django 4.0.4 on 2022-04-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupAccount',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('identifier', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=30, null=True)),
                ('creation_date_time', models.DateTimeField(blank=True, null=True)),
                ('last_modification_date_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'group_account',
            },
        ),
    ]
