# Generated by Django 4.0.3 on 2022-04-14 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupaccount',
            name='creation_date_time',
            field=models.DateTimeField(blank=True, db_column='creationDateTime', null=True),
        ),
        migrations.AlterField(
            model_name='groupaccount',
            name='identifier',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='groupaccount',
            name='last_modification_date_time',
            field=models.DateTimeField(blank=True, db_column='lastModificationDateTime', null=True),
        ),
        migrations.AlterField(
            model_name='groupaccount',
            name='password',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
