title: 온갖 - OTT 서비스 부가기능 통합 제공 웹 서비스
description: CAPSTONE-2022-24
show_downloads: true
darkmode: false
remote_theme: tuur29/pages-themes-cayman
color:
  header: "#ffffff"
  gradient_left: "#83bbfb"
  gradient_right: "#ffffff"
syntax_theme: https://stylishthemes.github.io/Syntax-Themes/pygments/css-github/pygments-monokai.css
buttons:
  zip_url: https://github.com/kookmin-sw/capstone-2022-24
  zip_title: View on GitHub
  zip_hide: false
  tar_hide: true
  github_hide: true