# Generated by Django 4.0.4 on 2022-05-25 23:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0002_alter_videodetail_video'),
        ('watching_marks', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='watchingmark',
            unique_together={('user', 'video')},
        ),
    ]
