"""Video View API descriptions"""
from drf_spectacular.utils import OpenApiExample

HOME_VIEW_EXAMPLE = [
    OpenApiExample(
        response_only=True,
        name="Success Example",
        value={
            "results": [
                {
                    "videoId": 1,
                    "title": "베놈",
                    "titleEnglish": "Venom",
                    "posterUrl": "https://image.tmdb.org/t/p/w500/x4ojC59pYfPlAP4mmy2LSkCCuK2.jpg",
                    "filmRating": None,
                    "releaseDate": 2018,
                    "category": "MV",
                    "providers": ["WV", "NF", "WC"],
                },
                {
                    "videoId": 2,
                    "title": "애프터",
                    "titleEnglish": "After",
                    "posterUrl": "https://image.tmdb.org/t/p/w500/zTZ7Q9mAwBQoYaR8HgGbmBNp6AC.jpg",
                    "filmRating": None,
                    "releaseDate": 2019,
                    "category": "MV",
                    "providers": ["NF", "WV"],
                },
                {
                    "videoId": 3,
                    "title": "킹덤: 아신전",
                    "titleEnglish": "Kingdom: Ashin of the North",
                    "posterUrl": "https://image.tmdb.org/t/p/w500/dBz61uAt6xjJt4yqhiZXQt0a1bB.jpg",
                    "filmRating": None,
                    "releaseDate": 2021,
                    "category": "MV",
                    "providers": ["NF"],
                },
                {
                    "videoId": 4,
                    "title": "보이카: 언디스퓨티드 파이널",
                    "titleEnglish": "Boyka: Undisputed IV",
                    "posterUrl": "https://image.tmdb.org/t/p/w500/bv58O1paP9cYlcOL7OEUwmzmDzy.jpg",
                    "filmRating": None,
                    "releaseDate": 2016,
                    "category": "MV",
                    "providers": ["NF", "WV"],
                },
                {
                    "videoId": 5,
                    "title": "싱크홀",
                    "titleEnglish": "Sinkhole",
                    "posterUrl": "https://image.tmdb.org/t/p/w500/l71a3Mh4PbOZwbIOlcsi3QcezK5.jpg",
                    "filmRating": None,
                    "releaseDate": 2021,
                    "category": "MV",
                    "providers": ["WV", "NF"],
                },
                {
                    "videoId": 6,
                    "title": "나는 어떻게 슈퍼히어로가 되었는가",
                    "titleEnglish": "How I Became a Superhero",
                    "posterUrl": "https://image.tmdb.org/t/p/w500/5UDe6oVAIv6PC7eJ046o6oCyQc3.jpg",
                    "filmRating": None,
                    "releaseDate": 2020,
                    "category": "MV",
                    "providers": ["NF"],
                },
                {
                    "videoId": 7,
                    "title": "헝거게임: 모킹제이",
                    "titleEnglish": "The Hunger Games: Mockingjay - Part 1",
                    "posterUrl": "https://image.tmdb.org/t/p/w500/r5UG5tSXpHIFFcpx4rvi6ZnJroj.jpg",
                    "filmRating": None,
                    "releaseDate": 2014,
                    "category": "MV",
                    "providers": ["NF", "WV"],
                },
                {
                    "videoId": 8,
                    "title": "인터스텔라",
                    "titleEnglish": "Interstellar",
                    "posterUrl": "https://image.tmdb.org/t/p/w500/zDNAeWU0PxKolEX1D8Vn1qWhGjH.jpg",
                    "filmRating": None,
                    "releaseDate": 2014,
                    "category": "MV",
                    "providers": ["NF", "WV", "WC"],
                },
                {
                    "videoId": 9,
                    "title": "바비: 빅 시티, 빅 드림스",
                    "titleEnglish": "Barbie: Big City, Big Dreams",
                    "posterUrl": "https://image.tmdb.org/t/p/w500/jeggetf6lrd0dhtcbqJH75Sik4K.jpg",
                    "filmRating": None,
                    "releaseDate": 2021,
                    "category": "MV",
                    "providers": ["NF"],
                },
                {
                    "videoId": 10,
                    "title": "돈 룩 업",
                    "titleEnglish": "Don't Look Up",
                    "posterUrl": "https://image.tmdb.org/t/p/w500/ri1eGoNoESMRKa8PXgmiBj2W3ve.jpg",
                    "filmRating": None,
                    "releaseDate": 2021,
                    "category": "MV",
                    "providers": ["NF"],
                },
                {
                    "videoId": 11,
                    "title": "메이의 새빨간 비밀",
                    "titleEnglish": "Turning Red",
                    "posterUrl": "https://image.tmdb.org/t/p/w500/hsOhOcX7qDy7bPwbrt1OoITngrf.jpg",
                    "filmRating": None,
                    "releaseDate": 2022,
                    "category": "MV",
                    "providers": ["DP"],
                },
                {
                    "videoId": 12,
                    "title": "닥터 스트레인지",
                    "titleEnglish": "Doctor Strange",
                    "posterUrl": "https://image.tmdb.org/t/p/w500/xA7ic72L0mejJX1SYMU38F7wwiF.jpg",
                    "filmRating": None,
                    "releaseDate": 2016,
                    "category": "MV",
                    "providers": ["WV", "DP"],
                },
                {
                    "videoId": 13,
                    "title": "엔칸토: 마법의 세계",
                    "titleEnglish": "Encanto",
                    "posterUrl": "https://image.tmdb.org/t/p/w500/b8gz7UKMwMz39mz6EH5Jjicjdth.jpg",
                    "filmRating": None,
                    "releaseDate": 2021,
                    "category": "MV",
                    "providers": ["DP"],
                },
                {
                    "videoId": 14,
                    "title": "이터널스",
                    "titleEnglish": "Eternals",
                    "posterUrl": "https://image.tmdb.org/t/p/w500/aNtAP8ZzUMdnCPoqYgVOcgI0Eh4.jpg",
                    "filmRating": None,
                    "releaseDate": 2021,
                    "category": "MV",
                    "providers": ["DP"],
                },
                {
                    "videoId": 16,
                    "title": "아바타",
                    "titleEnglish": "Avatar",
                    "posterUrl": "https://image.tmdb.org/t/p/w500/zygmx5abXeDpr3fWYX4jlXFZ1wh.jpg",
                    "filmRating": None,
                    "releaseDate": 2009,
                    "category": "MV",
                    "providers": ["WV", "DP"],
                },
                {
                    "videoId": 17,
                    "title": "킹스맨: 퍼스트 에이전트",
                    "titleEnglish": "The King's Man",
                    "posterUrl": "https://image.tmdb.org/t/p/w500/vOai6V9hsIqZu15zDKydPmzu4EN.jpg",
                    "filmRating": None,
                    "releaseDate": 2021,
                    "category": "MV",
                    "providers": ["WV", "DP"],
                },
                {
                    "videoId": 18,
                    "title": "캐리비안의 해적: 낯선 조류",
                    "titleEnglish": "Pirates of the Caribbean: On Stranger Tides",
                    "posterUrl": "https://image.tmdb.org/t/p/w500/osJVVjkHmoO5WoJfbBsImYrKWIb.jpg",
                    "filmRating": None,
                    "releaseDate": 2011,
                    "category": "MV",
                    "providers": ["DP", "WV"],
                },
                {
                    "videoId": 19,
                    "title": "캡틴 아메리카: 시빌 워",
                    "titleEnglish": "Captain America: Civil War",
                    "posterUrl": "https://image.tmdb.org/t/p/w500/vaMRzME3Dt73robEjOtDw4SPJGA.jpg",
                    "filmRating": None,
                    "releaseDate": 2016,
                    "category": "MV",
                    "providers": ["DP"],
                },
                {
                    "videoId": 20,
                    "title": "몬스터 주식회사",
                    "titleEnglish": "Monsters, Inc.",
                    "posterUrl": "https://image.tmdb.org/t/p/w500/fnDLrtEoIrxTCWUvuurMzOzQGpQ.jpg",
                    "filmRating": None,
                    "releaseDate": 2001,
                    "category": "MV",
                    "providers": ["WV", "DP"],
                },
                {
                    "videoId": 21,
                    "title": "꿈은 브로드웨이로 간다",
                    "titleEnglish": "Better Nate Than Ever",
                    "posterUrl": "https://image.tmdb.org/t/p/w500/bvMbnHBoliWanBTV4bqvB32dOAP.jpg",
                    "filmRating": None,
                    "releaseDate": 2022,
                    "category": "MV",
                    "providers": ["DP"],
                },
                {
                    "videoId": 22,
                    "title": "토르: 라그나로크",
                    "titleEnglish": "Thor: Ragnarok",
                    "posterUrl": "https://image.tmdb.org/t/p/w500/jwswXltzpGaKZCtz1CiDjXHQYAs.jpg",
                    "filmRating": None,
                    "releaseDate": 2017,
                    "category": "MV",
                    "providers": ["DP"],
                },
                {
                    "videoId": 23,
                    "title": "토르: 천둥의 신",
                    "titleEnglish": "Thor",
                    "posterUrl": "https://image.tmdb.org/t/p/w500/f99ngOw3HByxzT85EgUdd7MF8c4.jpg",
                    "filmRating": None,
                    "releaseDate": 2011,
                    "category": "MV",
                    "providers": ["DP", "WV"],
                },
                {
                    "videoId": 24,
                    "title": "라이온 킹",
                    "titleEnglish": "The Lion King",
                    "posterUrl": "https://image.tmdb.org/t/p/w500/9Y048zYw66TWvpUtsiNK0uReiVX.jpg",
                    "filmRating": None,
                    "releaseDate": 1994,
                    "category": "MV",
                    "providers": ["WV", "DP"],
                },
                {
                    "videoId": 25,
                    "title": "소울",
                    "titleEnglish": "Soul",
                    "posterUrl": "https://image.tmdb.org/t/p/w500/qJiaB4RJMM5Oh6A4rqrEOHQUJbu.jpg",
                    "filmRating": None,
                    "releaseDate": 2020,
                    "category": "MV",
                    "providers": ["DP"],
                },
            ],
            "page": {"limit": 24, "offset": 0, "totalCount": 227},
        },
    )
]

DETAIL_MOVIE_VIEW_EXAMPLE = [
    OpenApiExample(
        response_only=True,
        name="Success Example",
        value={
            "videoId": 10,
            "posterUrl": "https://image.tmdb.org/t/p/w500/tvhX4QQnMyMjlFeShLCXovvbf0c.jpg",
            "title": "마마듀크",
            "releaseYear": "2022",
            "releaseDate": "04-28",
            "titleEnglish": "Marmaduke",
            "overview": "사고뭉치 장난꾸러기 마마듀크. 따뜻한 마음씨를 지녔지만 늘 말썽이 끊이지 않는데. 화려한 도그 쇼 세계에서 빛나는 데 필요한 자질이 과연 마마듀크에게 있을까?",
            "providers": [
                {
                    "name": "NF",
                    "logoUrl": "https://image.tmdb.org/t/p/original/9A1JSVmSxsyaBK4SUFsYVqbAYfW.jpg",
                    "link": "https://www.netflix.com/kr/",
                }
            ],
            "genres": ["애니메이션", "가족", "코미디"],
            "productionCountries": ["캐나다", "미국"],
            "trailerUrl": "https://www.youtube.com/watch?v=F4v3vodCIkQ",
            "public": {"wishCount": 0, "watchCount": 0},
            "personal": {
                "wished": None,
                "watched": None,
            },
            "similars": [
                {"posterUrl": "https://image.tmdb.org/t/p/w500/im9hQmEX9me7vdTE1hHqT81Wjgo.jpg", "title": "빌리 엘리어트"},
                {"posterUrl": "https://image.tmdb.org/t/p/w500/hll4O5vSAfnZDb6JbnP06GPtz7b.jpg", "title": "화성침공"},
                {"posterUrl": "https://image.tmdb.org/t/p/w500/jnw5Ab8104n4rTkTootpfZKYPiZ.jpg", "title": "바람계곡의 나우시카"},
                {"posterUrl": "https://image.tmdb.org/t/p/w500/eBJEvKkhQ0tUt1dBAcTEYW6kCle.jpg", "title": "비버리 힐스 캅"},
                {"posterUrl": "https://image.tmdb.org/t/p/w500/egDakU8O5yUwpUJP9IMAUVtIDll.jpg", "title": "비버리 힐스 캅 2"},
                {"posterUrl": "https://image.tmdb.org/t/p/w500/bIqFRqtvE3pDSgamXGIAbVCxAKG.jpg", "title": "브루스 올마이티"},
            ],
        },
    )
]

DETAIL_TV_VIEW_EXAMPLE = [
    OpenApiExample(
        response_only=True,
        name="Success Example",
        value={
            "videoId": 4000,
            "posterUrl": "https://image.tmdb.org/t/p/w500/cezQyM5cO454vUdLiLOkv78K64D.jpg",
            "title": "스머프",
            "titleEnglish": "The Smurfs",
            "releaseYear": "1981",
            "releaseDate": "09-12",
            "filmRating": None,
            "overview": "",
            "providers": [
                {
                    "name": "NF",
                    "logoUrl": "https://image.tmdb.org/t/p/original/9A1JSVmSxsyaBK4SUFsYVqbAYfW.jpg",
                    "link": "https://www.netflix.com/kr/",
                }
            ],
            "genres": ["애니메이션", "가족", "Sci-Fi & Fantasy", "Kids"],
            "productionCountries": [],
            "totalSeasons": 9,
            "totalEpisodes": 422,
            "tralierUrl": "https://www.youtube.com/watch?v=gQMwc-lALC0",
            "seasons": [
                {"name": "스페셜", "number": 0},
                {"name": "시즌 1", "number": 1},
                {"name": "시즌 2", "number": 2},
                {"name": "시즌 3", "number": 3},
                {"name": "시즌 4", "number": 4},
                {"name": "시즌 5", "number": 5},
                {"name": "시즌 6", "number": 6},
                {"name": "시즌 7", "number": 7},
                {"name": "시즌 8", "number": 8},
                {"name": "시즌 9", "number": 9},
            ],
            "public": {"wishCount": 0, "watchCount": 0},
            "personal": {"wished": None, "watched": None},
            "similars": [
                {"posterUrl": "https://image.tmdb.org/t/p/w500/1LbPs6i1h4BKjVUwK5S9GjPCydi.jpg", "title": "로이스 앤 클락"},
                {"posterUrl": "https://image.tmdb.org/t/p/w500/jRGOY8KvL7hHrJcfKfXe99C4pc5.jpg", "title": "X-Men"},
                {
                    "posterUrl": "https://image.tmdb.org/t/p/w500/wa60s9NSvrH87NFCArmobnIyNnh.jpg",
                    "title": "The Incredible Hulk",
                },
                {
                    "posterUrl": "https://image.tmdb.org/t/p/w500/xqqZjLBUEOVAsXneUwITCuas9jL.jpg",
                    "title": "Fantastic Four",
                },
                {"posterUrl": "https://image.tmdb.org/t/p/w500/n6eMF2lPQxiGmh2D612R5Tuxbzm.jpg", "title": "스파이더맨"},
                {
                    "posterUrl": "https://image.tmdb.org/t/p/w500/vAvT2RXjOpgH0COriRm9riPqA0m.jpg",
                    "title": "The Boondocks",
                },
            ],
        },
    )
]
