"""Video View API descriptions"""
from drf_spectacular.utils import OpenApiExample

HOME_VIEW_EXAMPLE = [
    OpenApiExample(
        response_only=True,
        name="Success Example",
        value={
            "results": [
                {
                    "videoId": 1,
                    "title": "베놈",
                    "titleEnglish": "Venom",
                    "posterUrl": "https://image.tmdb.org/t/p/w500/x4ojC59pYfPlAP4mmy2LSkCCuK2.jpg",
                    "filmRating": None,
                    "releaseDate": 2018,
                    "category": "MV",
                    "providers": ["WV", "NF", "WC"],
                },
                {
                    "videoId": 2,
                    "title": "애프터",
                    "titleEnglish": "After",
                    "posterUrl": "https://image.tmdb.org/t/p/w500/zTZ7Q9mAwBQoYaR8HgGbmBNp6AC.jpg",
                    "filmRating": None,
                    "releaseDate": 2019,
                    "category": "MV",
                    "providers": ["NF", "WV"],
                },
                {
                    "videoId": 3,
                    "title": "킹덤: 아신전",
                    "titleEnglish": "Kingdom: Ashin of the North",
                    "posterUrl": "https://image.tmdb.org/t/p/w500/dBz61uAt6xjJt4yqhiZXQt0a1bB.jpg",
                    "filmRating": None,
                    "releaseDate": 2021,
                    "category": "MV",
                    "providers": ["NF"],
                },
                {
                    "videoId": 4,
                    "title": "보이카: 언디스퓨티드 파이널",
                    "titleEnglish": "Boyka: Undisputed IV",
                    "posterUrl": "https://image.tmdb.org/t/p/w500/bv58O1paP9cYlcOL7OEUwmzmDzy.jpg",
                    "filmRating": None,
                    "releaseDate": 2016,
                    "category": "MV",
                    "providers": ["NF", "WV"],
                },
                {
                    "videoId": 5,
                    "title": "싱크홀",
                    "titleEnglish": "Sinkhole",
                    "posterUrl": "https://image.tmdb.org/t/p/w500/l71a3Mh4PbOZwbIOlcsi3QcezK5.jpg",
                    "filmRating": None,
                    "releaseDate": 2021,
                    "category": "MV",
                    "providers": ["WV", "NF"],
                },
                {
                    "videoId": 6,
                    "title": "나는 어떻게 슈퍼히어로가 되었는가",
                    "titleEnglish": "How I Became a Superhero",
                    "posterUrl": "https://image.tmdb.org/t/p/w500/5UDe6oVAIv6PC7eJ046o6oCyQc3.jpg",
                    "filmRating": None,
                    "releaseDate": 2020,
                    "category": "MV",
                    "providers": ["NF"],
                },
                {
                    "videoId": 7,
                    "title": "헝거게임: 모킹제이",
                    "titleEnglish": "The Hunger Games: Mockingjay - Part 1",
                    "posterUrl": "https://image.tmdb.org/t/p/w500/r5UG5tSXpHIFFcpx4rvi6ZnJroj.jpg",
                    "filmRating": None,
                    "releaseDate": 2014,
                    "category": "MV",
                    "providers": ["NF", "WV"],
                },
                {
                    "videoId": 8,
                    "title": "인터스텔라",
                    "titleEnglish": "Interstellar",
                    "posterUrl": "https://image.tmdb.org/t/p/w500/zDNAeWU0PxKolEX1D8Vn1qWhGjH.jpg",
                    "filmRating": None,
                    "releaseDate": 2014,
                    "category": "MV",
                    "providers": ["NF", "WV", "WC"],
                },
                {
                    "videoId": 9,
                    "title": "바비: 빅 시티, 빅 드림스",
                    "titleEnglish": "Barbie: Big City, Big Dreams",
                    "posterUrl": "https://image.tmdb.org/t/p/w500/jeggetf6lrd0dhtcbqJH75Sik4K.jpg",
                    "filmRating": None,
                    "releaseDate": 2021,
                    "category": "MV",
                    "providers": ["NF"],
                },
                {
                    "videoId": 10,
                    "title": "돈 룩 업",
                    "titleEnglish": "Don't Look Up",
                    "posterUrl": "https://image.tmdb.org/t/p/w500/ri1eGoNoESMRKa8PXgmiBj2W3ve.jpg",
                    "filmRating": None,
                    "releaseDate": 2021,
                    "category": "MV",
                    "providers": ["NF"],
                },
                {
                    "videoId": 11,
                    "title": "메이의 새빨간 비밀",
                    "titleEnglish": "Turning Red",
                    "posterUrl": "https://image.tmdb.org/t/p/w500/hsOhOcX7qDy7bPwbrt1OoITngrf.jpg",
                    "filmRating": None,
                    "releaseDate": 2022,
                    "category": "MV",
                    "providers": ["DP"],
                },
                {
                    "videoId": 12,
                    "title": "닥터 스트레인지",
                    "titleEnglish": "Doctor Strange",
                    "posterUrl": "https://image.tmdb.org/t/p/w500/xA7ic72L0mejJX1SYMU38F7wwiF.jpg",
                    "filmRating": None,
                    "releaseDate": 2016,
                    "category": "MV",
                    "providers": ["WV", "DP"],
                },
                {
                    "videoId": 13,
                    "title": "엔칸토: 마법의 세계",
                    "titleEnglish": "Encanto",
                    "posterUrl": "https://image.tmdb.org/t/p/w500/b8gz7UKMwMz39mz6EH5Jjicjdth.jpg",
                    "filmRating": None,
                    "releaseDate": 2021,
                    "category": "MV",
                    "providers": ["DP"],
                },
                {
                    "videoId": 14,
                    "title": "이터널스",
                    "titleEnglish": "Eternals",
                    "posterUrl": "https://image.tmdb.org/t/p/w500/aNtAP8ZzUMdnCPoqYgVOcgI0Eh4.jpg",
                    "filmRating": None,
                    "releaseDate": 2021,
                    "category": "MV",
                    "providers": ["DP"],
                },
                {
                    "videoId": 16,
                    "title": "아바타",
                    "titleEnglish": "Avatar",
                    "posterUrl": "https://image.tmdb.org/t/p/w500/zygmx5abXeDpr3fWYX4jlXFZ1wh.jpg",
                    "filmRating": None,
                    "releaseDate": 2009,
                    "category": "MV",
                    "providers": ["WV", "DP"],
                },
                {
                    "videoId": 17,
                    "title": "킹스맨: 퍼스트 에이전트",
                    "titleEnglish": "The King's Man",
                    "posterUrl": "https://image.tmdb.org/t/p/w500/vOai6V9hsIqZu15zDKydPmzu4EN.jpg",
                    "filmRating": None,
                    "releaseDate": 2021,
                    "category": "MV",
                    "providers": ["WV", "DP"],
                },
                {
                    "videoId": 18,
                    "title": "캐리비안의 해적: 낯선 조류",
                    "titleEnglish": "Pirates of the Caribbean: On Stranger Tides",
                    "posterUrl": "https://image.tmdb.org/t/p/w500/osJVVjkHmoO5WoJfbBsImYrKWIb.jpg",
                    "filmRating": None,
                    "releaseDate": 2011,
                    "category": "MV",
                    "providers": ["DP", "WV"],
                },
                {
                    "videoId": 19,
                    "title": "캡틴 아메리카: 시빌 워",
                    "titleEnglish": "Captain America: Civil War",
                    "posterUrl": "https://image.tmdb.org/t/p/w500/vaMRzME3Dt73robEjOtDw4SPJGA.jpg",
                    "filmRating": None,
                    "releaseDate": 2016,
                    "category": "MV",
                    "providers": ["DP"],
                },
                {
                    "videoId": 20,
                    "title": "몬스터 주식회사",
                    "titleEnglish": "Monsters, Inc.",
                    "posterUrl": "https://image.tmdb.org/t/p/w500/fnDLrtEoIrxTCWUvuurMzOzQGpQ.jpg",
                    "filmRating": None,
                    "releaseDate": 2001,
                    "category": "MV",
                    "providers": ["WV", "DP"],
                },
                {
                    "videoId": 21,
                    "title": "꿈은 브로드웨이로 간다",
                    "titleEnglish": "Better Nate Than Ever",
                    "posterUrl": "https://image.tmdb.org/t/p/w500/bvMbnHBoliWanBTV4bqvB32dOAP.jpg",
                    "filmRating": None,
                    "releaseDate": 2022,
                    "category": "MV",
                    "providers": ["DP"],
                },
                {
                    "videoId": 22,
                    "title": "토르: 라그나로크",
                    "titleEnglish": "Thor: Ragnarok",
                    "posterUrl": "https://image.tmdb.org/t/p/w500/jwswXltzpGaKZCtz1CiDjXHQYAs.jpg",
                    "filmRating": None,
                    "releaseDate": 2017,
                    "category": "MV",
                    "providers": ["DP"],
                },
                {
                    "videoId": 23,
                    "title": "토르: 천둥의 신",
                    "titleEnglish": "Thor",
                    "posterUrl": "https://image.tmdb.org/t/p/w500/f99ngOw3HByxzT85EgUdd7MF8c4.jpg",
                    "filmRating": None,
                    "releaseDate": 2011,
                    "category": "MV",
                    "providers": ["DP", "WV"],
                },
                {
                    "videoId": 24,
                    "title": "라이온 킹",
                    "titleEnglish": "The Lion King",
                    "posterUrl": "https://image.tmdb.org/t/p/w500/9Y048zYw66TWvpUtsiNK0uReiVX.jpg",
                    "filmRating": None,
                    "releaseDate": 1994,
                    "category": "MV",
                    "providers": ["WV", "DP"],
                },
                {
                    "videoId": 25,
                    "title": "소울",
                    "titleEnglish": "Soul",
                    "posterUrl": "https://image.tmdb.org/t/p/w500/qJiaB4RJMM5Oh6A4rqrEOHQUJbu.jpg",
                    "filmRating": None,
                    "releaseDate": 2020,
                    "category": "MV",
                    "providers": ["DP"],
                },
            ],
            "page": {"limit": 24, "offset": 0, "totalCount": 227},
        },
    )
]

DETAIL_MOVIE_VIEW_EXAMPLE = [
    OpenApiExample(
        response_only=True,
        name="Success Example",
        value={
            "videoId": 60,
            "posterUrl": "https://image.tmdb.org/t/p/w500/2R8smeSDkPx6TKIRveKPXi0JVI6.jpg",
            "title": "언차티드",
            "releaseYear": "2022",
            "releaseDate": "02-10",
            "titleEnglish": "Uncharted",
            "overview": (
                "평범한 삶을 살던 네이선은 인생을 바꿀 뜻밖의 제안을 받는다. 그의 미션은 크루와 함께 사라진 형과 500년 전 잃어버린 천문학적인 가치를"
                " 지닌 트레져를 찾아내는 것. 그러나 몬카다의 위협 속, 누구보다 빠르게 미지의 세계에 닿기 위해 결단을 내려야만 하는데…"
            ),
            "providers": [
                {
                    "name": "WV",
                    "logoUrl": "https://image.tmdb.org/t/p/original/8N0DNa4BO3lH24KWv1EjJh4TxoD.jpg",
                    "link": "https://www.wavve.com/",
                }
            ],
            "genres": ["액션", "모험"],
            "productionCountries": ["미국"],
            "public": {"wishCount": 0, "watchCount": 1},
            "personal": {"wished": False, "watched": True},
            "similars": [
                {"posterUrl": "https://image.tmdb.org/t/p/w500/SkNd3gVm26389N5jPaCM5hpekh.jpg", "title": "몬테 크리스토"},
                {"posterUrl": "https://image.tmdb.org/t/p/w500/mtmb7GMXXQOpMH9Bkgka4xy18lu.jpg", "title": "스트리트 파이터"},
                {
                    "posterUrl": "https://image.tmdb.org/t/p/w500/w1SlfdoU144Sl4c8rXG9kw5jiuq.jpg",
                    "title": "포켓몬스터 극장판 - 뮤츠의 역습",
                },
                {
                    "posterUrl": "https://image.tmdb.org/t/p/w500/p2Hkd6iJ3Hu3MJbzHkyzd40zBSy.jpg",
                    "title": "ソニック★ザ★ヘッジホッグ",
                },
                {"posterUrl": "https://image.tmdb.org/t/p/w500/o6Wf8lj8P9enQQbj4pC8jVDJHxI.jpg", "title": "어둠 속에 나홀로"},
                {
                    "posterUrl": "https://image.tmdb.org/t/p/w500/a4sHmafOKKOTo2TZYtvy9CufVTz.jpg",
                    "title": "포켓몬스터 극장판 - 루기아의 탄생",
                },
            ],
        },
    )
]

DETAIL_TV_VIEW_EXAMPLE = [
    OpenApiExample(
        response_only=True,
        name="Success Example",
        value={
            "videoId": 200,
            "posterUrl": "https://image.tmdb.org/t/p/w500/ekp9PbSODHiTXXqnHJ4Sq6YHkhq.jpg",
            "title": "블리치",
            "titleEnglish": "Bleach",
            "releaseYear": "2004",
            "releaseDate": "10-05",
            "filmRating": None,
            "overview": "",
            "providers": [
                {
                    "name": "WV",
                    "logoUrl": "https://image.tmdb.org/t/p/original/8N0DNa4BO3lH24KWv1EjJh4TxoD.jpg",
                    "link": "https://www.wavve.com/",
                }
            ],
            "genres": ["Action & Adventure", "애니메이션", "Sci-Fi & Fantasy"],
            "productionCountries": ["일본"],
            "totalSeasons": 1,
            "totalEpisodes": 366,
            "seasons": [{"number": 0, "name": "스페셜"}, {"number": 1, "name": "시즌 1"}],
            "public": {"wishCount": 1, "watchCount": 5},
            "personal": {"wished": True, "watched": True},
            "similars": [
                {"posterUrl": "https://image.tmdb.org/t/p/w500/97vxf06BrfiSuZJ5a03RuOHNyP0.jpg", "title": "진격의 거인"},
                {
                    "posterUrl": "https://image.tmdb.org/t/p/w500/pOjDuclpsWGV13Nj7XtZukuZj6f.jpg",
                    "title": "소녀혁명 우테나",
                },
                {
                    "posterUrl": "https://image.tmdb.org/t/p/w500/9A7q9QjLoTfYLn7zejj7uRYA3IZ.jpg",
                    "title": "오란고교 사교클럽",
                },
                {
                    "posterUrl": "https://image.tmdb.org/t/p/w500/ej3tcxv2YYVWy6WoOeWZTcrkiI8.jpg",
                    "title": "시리얼 익스페러먼츠 레인",
                },
                {
                    "posterUrl": "https://image.tmdb.org/t/p/w500/wXaWK1dtA5EACL3ASDKGKBJePsS.jpg",
                    "title": "에르고 프록시",
                },
                {
                    "posterUrl": "https://image.tmdb.org/t/p/w500/fbdM3vtY29PkipKrBb6NuTw7VDt.jpg",
                    "title": "교향시편 유레카 세븐",
                },
            ],
        },
    )
]
