# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: dev-fe-ci

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: fe-dev-ci
    defaults:
      run:
        working-directory: src/front-end
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    steps:
    - uses: actions/checkout@v2
    - name: Create .env.local File for Develop environments
      run: |
        echo "${{ secrets.ENV }}" > .env.local
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: src/front-end/package-lock.json
    - name: Install dependency packages
      run: npm ci
    - name: Build project
      run: npm run build --if-present
#    - name: Run unit tests
#      run: npm run test:unit
#    - name: Run e2e test
#      run: npm run test:e2e
    - name: Check code styles
      run: npm run lint
